# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_broker.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14message_broker.proto\x12\x0emessage_broker\"0\n\x0ePublishRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x0fPublishResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"!\n\x10SubscribeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"9\n\x07Message\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06sender\x18\x03 \x01(\t\"\x07\n\x05\x45mpty\" \n\x0eTopicsResponse\x12\x0e\n\x06topics\x18\x01 \x03(\t2\xe9\x01\n\rMessageBroker\x12J\n\x07Publish\x12\x1e.message_broker.PublishRequest\x1a\x1f.message_broker.PublishResponse\x12H\n\tSubscribe\x12 .message_broker.SubscribeRequest\x1a\x17.message_broker.Message0\x01\x12\x42\n\tGetTopics\x12\x15.message_broker.Empty\x1a\x1e.message_broker.TopicsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_broker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUBLISHREQUEST']._serialized_start=40
  _globals['_PUBLISHREQUEST']._serialized_end=88
  _globals['_PUBLISHRESPONSE']._serialized_start=90
  _globals['_PUBLISHRESPONSE']._serialized_end=124
  _globals['_SUBSCRIBEREQUEST']._serialized_start=126
  _globals['_SUBSCRIBEREQUEST']._serialized_end=159
  _globals['_MESSAGE']._serialized_start=161
  _globals['_MESSAGE']._serialized_end=218
  _globals['_EMPTY']._serialized_start=220
  _globals['_EMPTY']._serialized_end=227
  _globals['_TOPICSRESPONSE']._serialized_start=229
  _globals['_TOPICSRESPONSE']._serialized_end=261
  _globals['_MESSAGEBROKER']._serialized_start=264
  _globals['_MESSAGEBROKER']._serialized_end=497
# @@protoc_insertion_point(module_scope)
